# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao_pro', models.TextField(blank=True, null=True)),
                ('avaliacao_contra', models.TextField(blank=True, null=True)),
                ('recomendacoes', models.TextField(blank=True, null=True)),
                ('last_update', models.DateTimeField(verbose_name='Ultima atualização')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='avaliacao/fotos', verbose_name='foto-01')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('upload_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Avaliacao',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['ferramenta'],
            },
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('link_download', models.CharField(blank=True, max_length=100, verbose_name='link_download')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('upload_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nivel_professor', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediário', 'Intermediário'), ('profissional', 'Profissional')], default='iniciante', max_length=15, verbose_name='nivel de exeperiência do Professor')),
                ('nivel_aluno', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediário', 'Intermediário'), ('profissional', 'Profissional')], default='iniciante', max_length=15, verbose_name='nivel de exeperiência do Aluno')),
                ('requisitos_sistema', models.TextField(blank=True, null=True, verbose_name='requisitos do sistema')),
                ('indicacao_pedagogica', models.CharField(blank=True, max_length=100, verbose_name='Indicação de Ensino Pedagógico')),
            ],
            options={
                'verbose_name': 'Ferramenta',
                'verbose_name_plural': 'Ferramentas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='ferramenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.Ferramenta'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Usuario'),
        ),
    ]
