# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_auto_20170823_0913'),
    ]

    operations = [
        
    ]
