# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0003_remove_ferramenta_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='Categoria',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='avaliacao.Categoria'),
            preserve_default=False,
        ),
    ]
