# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('avaliacao', '0006_remove_avaliacao_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.Usuario'),
            preserve_default=False,
        ),
    ]
