# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-23 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0008_auto_20170823_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='imagem',
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='avaliacao/imagens', verbose_name='foto-01'),
        ),
    ]
