# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-01 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0009_auto_20170823_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ferramenta',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='avaliacao/imagem', verbose_name='foto-01'),
        ),
    ]
