# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-12 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0015_auto_20170912_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferramenta',
            name='nivel_aluno',
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='nivel_professor',
        ),
    ]
