# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0017_auto_20170912_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima atualização'),
        ),
    ]
