# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 14:42
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefone', models.CharField(blank=True, max_length=16)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('cnpj', models.CharField(blank=True, max_length=16, null=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=140, null=True, verbose_name='Endereço')),
                ('profissao', models.CharField(blank=True, max_length=80)),
                ('trocar_senha', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('esperiencia', models.TextField(blank=True, null=True)),
                ('start_date_acesso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data inicio acesso')),
                ('final_date_acesso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data final acesso')),
                ('id_rede_social', models.CharField(blank=True, max_length=32)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accounts/img', verbose_name='Imagem')),
                ('cidade', models.CharField(blank=True, max_length=50)),
                ('uf', models.CharField(choices=[('Acre', 'AC'), ('Alagoas', 'AL'), ('Amapá', 'AP'), ('Amazonas', 'AM'), ('Bahia', 'BA'), ('Ceará', 'CE'), ('Distrito Federal', 'DF'), ('Espírito Santo', 'ES'), ('Goiás', 'GO'), ('Maranhão', 'MA'), ('Mato Grosso', 'MT'), ('Mato Grosso do Sul', 'MS'), ('Minas Gerais', 'MG'), ('Pará', 'PA'), ('Paraíba', 'PB'), ('Paraná', 'PR'), ('Pernambuco', 'PE'), ('Piauí', 'PI'), ('Rio de Janeiro', 'RJ'), ('Rio Grande do Norte', 'RN'), ('Rio Grande do Sul', 'RS'), ('Rondônia', 'RO'), ('Roraima', 'RR'), ('Santa Catarina', 'SC'), ('São Paulo', 'SP'), ('Sergipe', 'SE'), ('Tocantins', 'TO'), ('--- --- ---', '---')], default='---', max_length=35)),
                ('nivel_acesso', models.CharField(choices=[('administrador', 'Administrador'), ('professor', 'Professor'), ('aluno', 'Aluno'), ('usuario', 'usuario')], default='professor', max_length=15)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'alunoespecial_usuario',
                'permissions': (('adicionar_usuario', 'Pode adicionar Usuario'), ('editar_usuario', 'Pode editar Usuario'), ('visualizar_usuario', 'Pode visualizar Usuario'), ('deletar_usuario', 'Pode deletar Usuario')),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
