# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-10 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='esperiencia',
        ),
        migrations.AddField(
            model_name='usuario',
            name='experiencia',
            field=models.TextField(blank=True, null=True, verbose_name='Experiência'),
        ),
    ]
